# -*- coding: utf-8 -*-
"""Data Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ay-2mG8acqmEbzuW8ijzv1vsJNjkxg90

Importing the Libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Importing the DataSet

"""

dataset = pd.read_csv('/Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

print(x)

print(y)

"""Taking Care of Missing Data"""

from sklearn.impute import simpleImputer